#!/bin/bash

base="${1:-$PWD}"
kawamura="${base%/Ret395/*}/Ret395/Kawamura_data"

export GNUPLOT_LIB="$base/scripts:$kawamura"
for i in "$base/scripts"/{U,k,omega,nut,T,alphat}.gpi; do
	gnuplot -c "$i"
done
