#!/bin/bash

base="${1:-$PWD}"
kawamura="${base%/Ret395/*}/Ret395/Kawamura_data"

export GNUPLOT_LIB="$base/scripts:$kawamura"
for i in {U,k,epsilon,nut,{alphat,T}{0025,071,1,2,5,7,10},key{,T}}.gpi; do
	gnuplot -c "$i"
done

convert key.png -trim -border 1x1 -bordercolor white +repage key.png
convert keyT.png -trim -border 1x1 -bordercolor white +repage keyT.png
