#!/bin/bash

base="${1:-$PWD}"
kawamura="${base%/Ret640/*}/Ret640/Kawamura_data"

export GNUPLOT_LIB="$base/scripts:$kawamura"
for i in {U,k,epsilon,nut,{alphat,T}{0025,071},key{,T}}.gpi; do
	gnuplot -c "$i"
done

convert key.png -trim -border 1x1 -bordercolor white +repage key.png
convert keyT.png -trim -border 1x1 -bordercolor white +repage keyT.png

pushd ../..
./scripts/norms 640 Ret640/tau/LSkEps/mesh5/ Ret640/bulk/LSkEps/mesh5/ Ret640/bulk/kOmegaSST/reAnalogy/mesh5/ Ret640/bulk/kOmegaSST/{manservisi,kay,AHFM,kt-wt}/*/mesh5 > Ret640/comparison/norms640.dat
popd

