#!/bin/bash

base="${1:-$PWD}"
kawamura="${base%/Ret640/*}/Ret640/Kawamura_data"

export GNUPLOT_LIB="$base/scripts:$kawamura"
for i in "$base/scripts"/{U,k,epsilon,nut}.gpi; do
	gnuplot -c "$i"
done
