#!/bin/bash

base="${1:-$PWD}"
kawamura="${base%/Ret640/*}/Ret640/Kawamura_data"

export GNUPLOT_LIB="$base/scripts:$kawamura"
for i in "$base/scripts4"/{U,k,epsilon,nut,T{0025,071}}.gpi; do
	gnuplot -c "$i"
done
