#!/bin/bash

base="${1:-$PWD}"
kawamura="${base%/Ret640/*}/Ret640/Kawamura_data"

export GNUPLOT_LIB="$kawamura"
for i in {U,k,epsilon,nut,{alphat,T,kt}{0025,071}}.gpi; do
	gnuplot -c png.gpi "$i" "${i%.gpi}.png"
	gnuplot -c pngsemilog.gpi "$i" "${i%.gpi}-semilog.png"
done

for i in key{U,T,kt}.gpi; do
	png="${i%.gpi}.png"
	gnuplot -c png.gpi "$i" "$png"
	convert "$png" -trim -border 1x1 -bordercolor white +repage "$png"
done

pushd ../..
./scripts/norms 640 Ret640/tau/LSkEps/mesh4/ Ret640/bulk/LSkEps/mesh4/ Ret640/bulk/kOmegaSST/reAnalogy/mesh4/ Ret640/bulk/kOmegaSST/{manservisi,kay,AHFM,nrgAHFM,kt-wt,kays2}/*/mesh5 > Ret640/presentation_plots2/norms640.dat
popd

awk 'BEGIN{FIXEDWIDTHS="10 6 60 16 15 15 15 15 15"}$3~/reAnalogy/   &&$1~/T[0-9]/{print $2,$5}' norms640.dat | sort -k1,1g > reAnalogykOmega.dat
awk 'BEGIN{FIXEDWIDTHS="10 6 60 16 15 15 15 15 15"}$3~/bulk\/LSkEps/&&$1~/T[0-9]/{print $2,$5}' norms640.dat | sort -k1,1g > reAnalogyLSkEps.dat
awk 'BEGIN{FIXEDWIDTHS="10 6 60 16 15 15 15 15 15"}$3~/tau\/LSkEps/ &&$1~/T[0-9]/{print $2,$5}' norms640.dat | sort -k1,1g > reAnalogytauLSkEps.dat
awk 'BEGIN{FIXEDWIDTHS="10 6 60 16 15 15 15 15 15"}$3~/manservisi/  &&$1~/T$/{print $2,$5}'     norms640.dat | sort -k1,1g > manservisi.dat
awk 'BEGIN{FIXEDWIDTHS="10 6 60 16 15 15 15 15 15"}$3~/kt-wt/       &&$1~/T$/{print $2,$5}'     norms640.dat | sort -k1,1g > kt-wt.dat
awk 'BEGIN{FIXEDWIDTHS="10 6 60 16 15 15 15 15 15"}$3~/kay\//       &&$1~/T$/{print $2,$5}'     norms640.dat | sort -k1,1g > kay.dat
awk 'BEGIN{FIXEDWIDTHS="10 6 60 16 15 15 15 15 15"}$3~/kays2/       &&$1~/T$/{print $2,$5}'     norms640.dat | sort -k1,1g > kays2.dat
awk 'BEGIN{FIXEDWIDTHS="10 6 60 16 15 15 15 15 15"}$3~/\/AHFM/      &&$1~/T$/{print $2,$5}'     norms640.dat | sort -k1,1g > AHFM.dat
awk 'BEGIN{FIXEDWIDTHS="10 6 60 16 15 15 15 15 15"}$3~/\/nrgAHFM/   &&$1~/T$/{print $2,$5}'     norms640.dat | sort -k1,1g > nrgAHFM.dat

gnuplot -c pngerrors.gpi errors.gpi errors.png
gnuplot -c pngerrors.gpi keyerrors.gpi keyerrors.png
convert keyerrors.png -trim -border 1x1 -bordercolor white +repage keyerrors.png
